// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fihzmirdzsqxgkzdfuvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpaHptaXJkenNxeGdremRmdXZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNTc1MzcsImV4cCI6MjA1MzgzMzUzN30.1Taq63dDdDC2m-HCSivrh6wKkikz_kVoIJT1ATUzaT0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);